### ISSUE TITLE
Add end-to-end testing

### ISSUE THREAD

**Issue by lauriii** [acquia/next-acms#25]
Add end-to-end testing that ensures that the starter-kit works with ACMS. This includes setting up testing infrastructure on Github Actions that installs Drupal and the basic starterkit, and runs the test cases.

**Comment by phenaproxima** [comment]
@lauriii, I don't know enough about Cypress yet to have an opinion on this, but I'm wondering: do we care very much about implementing test isolation similar to what Drupal core's PHPUnit testing has?

I ask because that could be really tricky, since setting up a starter kit app is a very involved endeavor with a million dependencies, so I doubt it will be feasible to spin up a new one for every test case.

**Comment by lauriii** [comment]
End to end testing has been added and is being run on CI. Thank you for working on this @phenaproxima!
