### ISSUE TITLE
Provide an index/landing page

### ISSUE THREAD

**Issue by balsama** [acquia/next-acms#31]
Right now, the homepage is a 404. This is a bad out of the box experience and also doesn't demonstrate _how_ to create an index page using the starterkit. (In fact, creating an index.tsx file conflicts with the [`[[...slug]].tsx`](https://github.com/acquia/next-acms/blob/main/starters/basic-starter/pages/%5B%5B...slug%5D%5D.tsx) file.

**Comment by fiasco** [comment]
That was because the demo content in Acquia CMS used the Page content type for the front page and that content type used Site Studio for its content. Because Site Studio wasn’t in the headless CMS, the demo content went missing and caused a 404 front page (which it previously did not).

In #34, I like that this index.tsx page (that replaces the frontpage 404) can show how to display content aggregates though I’m not super sure about removing editorial control of the frontpage away from the CMS users.

**Comment by lauriii** [comment]
> In https://github.com/acquia/next-acms/pull/34, I like that this index.tsx page (that replaces the frontpage 404) can show how to display content aggregates though I’m not super sure about removing editorial control of the frontpage away from the CMS users.

Do you mean that the texts on the frontpage should be editable from Drupal? Or do you mean that editors should be able to change which path is rendered as the frontpage from Drupal?

**Comment by lauriii** [comment]
Discussed with @fiasco and his comment was about former. I think we could open another issue for adding support for creating an example of rendering blocks in Next.js that could be edited in Drupal.

**Comment by lauriii** [comment]
Discussed with @fiasco and we agreed that this can be closed. We have an issue for adding support for block like content: https://github.com/acquia/next-acms/issues/46.
